# Generated by Django 4.1.2 on 2022-11-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='book_name',
            new_name='book',
        ),
    ]
